name: "Comvent - Comment Event"
description: "Fast parsing of comment event"
author: "rytswd"
inputs:
  keyword:
    description: "Keyword to search in the comment; this uses a regex"
runs:
  using: "node12"
  main: "lib/main.js"
