---
name: Feature Request
description: File a feature request
title: "[Feature Request]: "
labels: [enhancement]
# assignees:
#   - rytswd
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a feature request!
  - type: dropdown
    id: enhancement-area
    attributes:
      label: Enhancement Area
      description: Select all the areas that are a part of the feature
      multiple: true
      options:
        - GitHub Action Input
        - Issue Comment Event Handling
        - Pull Request Comment Event Handling
        - Comvent Configuration YAML
        - Runtime
        - Other
    validations:
      required: true
  - type: textarea
    id: request-details
    attributes:
      label: Details
      description: Please provide some overview of proposed request, and how it is useful
      placeholder: Background, rationale, pain points, etc.
    validations:
      required: true
