name: Comvent Parse
on: issue_comment

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: rytswd/comvent@v0.1-release
        id: comvent
        with:
          keyword: jkl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Some random method
        run: |
          echo Just says something
      - name: Run when comvent matches
        run: |
          echo This message means comvent found the comment event with the matching keyword
        if: steps.comvent.found == 'passed'
