name: Comvent Parse
on: issue_comment

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: lalala
        run: |
          cat /github/workflow/event.json
          echo This is a test
          set
      - uses: rytswd/comvent@v0.1-release
        with:
          keyword: jkl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
