name: Comvent Parse
on: issue_comment

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: lalala
        run: |
          echo This is a test
          set
      - uses: rytswd/comvent@v0.0.1
        with:
          keyword: def
