name: Comvent - Simple demo with Whitelist
on:
  issue_comment:
    # This shouldn't be called for comment deletion
    types:
      - created
      - edited

jobs:
  comvent-simple:
    name: With latest code base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Parse comment
        uses: ./
        id: comvent
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/comvent-whitelist-demo.yaml

      - if: steps.comvent.outputs.command-random != ''
        name: Command random triggered
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `Command \`/random\` was triggered by the comment`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })

      - if: steps.comvent.outputs.command-today != ''
        name: Command today triggered
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `Command \`/today\` was triggered by the comment`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })

      - if: steps.comvent.outputs.command-httpbin != ''
        name: Command httpbin triggered
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `Command \`/httpbin\` was triggered by the comment`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })
