name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: With Default
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-check-only: yes
      - name: test
        run: |
          pwd ; ls -latr
      - uses: ./
        name: With Custom Config
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/comvent-whitelist-demo.yaml
          config-check-only: yes
